name: postal
version: 2.1.0
home: https://github.com/linkyard/postal-kubernetes
description: A complete and fully featured mail server
keywords:
  - postal
sources:
  - https://github.com/linkyard/postal-kubernetes
maintainers:
  - name: Ferdinand Hübner
    email: ferdinand.huebner@linkyard.ch
engine: gotpl
